encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.chosen, name="chosen"),
    path("create", views.create, name="create"),
    path("search", views.search, name="search"),
    path("random", views.random, name="random"),    
    path("edit", views.edit, name="edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from . import util
import markdown2
import random


NameList = util.list_entries()
TolowerNamelist = [element.lower() for element in NameList]
RandomName = random.choice(TolowerNamelist)
TITLE = ""

class NewTaskForm(forms.Form):
    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={'class': 'form-control'})) 
    text = forms.CharField(label="Text", widget=forms.Textarea(attrs={'class': 'form-control'}))

class NewTaskForm2(forms.Form):
    title = forms.CharField(label="") 
form2 = NewTaskForm2()

class NewTaskForm3(forms.Form):
    text = forms.CharField(label="Text", widget=forms.Textarea())

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": NameList, 
        "form2":form2,
    })

def chosen(request, title):

    global TITLE
    if len(TITLE) == 0:
        TITLE += title
    else:
        while(len(TITLE) != 0):
            TITLE = TITLE.replace(TITLE[len(TITLE) - 1], "")
        TITLE += title

    dirty_text = util.get_entry(title)
    text = markdown2.markdown(dirty_text)
    return render(request, "encyclopedia/chosen.html", {
        "title": title,
        "text": text,
        "form2":form2
    })

def create(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if not form.is_valid():
            return render(request, "encyclopedia/chosen-nobut.html", {
                "message":"You have to input the form",
                "form2":form2
            })

        title = form.cleaned_data["title"]
        text = form.cleaned_data["text"]
        if title.lower() not in TolowerNamelist:
            NameList.append(title)
            with open(f"entries/{title}.md", 'w') as file:
                title2 = "#" + title + "\n"
                file.write(title2)
                file.write(text) 
            html2 = util.get_entry(title)
            text = markdown2.markdown(html2)
            return HttpResponseRedirect(f"/wiki/{title}")

        else:
            return render(request, "encyclopedia/chosen-nobut.html", {
                "message":"Such file already exists", 
                "form2":form2
            })
        
    else: 
        return render(request, "encyclopedia/create.html", {
            "form":NewTaskForm(), 
            "form2":form2
        })
    
def search(request):
    form2 = NewTaskForm2(request.GET)      
    if not form2.is_valid():
        return render(request, "encyclopedia/chosen.html", {
            "title":"The filename was not inputed", 
            "form2":form2
        })


    title = form2.cleaned_data["title"]
    if title.lower() not in TolowerNamelist:
        return render(request, "encyclopedia/chosen.html", {
            "title":"Such filename does not exist", 
            "form2":form2
        })

    global TITLE
    if len(TITLE) == 0:
        TITLE += title
    else:
        while(len(TITLE) != 0):
            TITLE = TITLE.replace(TITLE[len(TITLE) - 1], "")
        TITLE += title

    html = util.get_entry(title)
    text = markdown2.markdown(html)
    return render(request, "encyclopedia/chosen.html", {
        "title":title, 
        "text":text, 
        "form2":form2, 
    })     

def random(request):
    title = RandomName
    html = util.get_entry(title)
    text = markdown2.markdown(html)
    return render(request, "encyclopedia/chosen.html", {
        "title":title, 
        "text":text, 
        "form2":form2
    })   

def edit(request):
    title = TITLE
    if request.method == "POST":  
        form = NewTaskForm3(request.POST)
        if not form.is_valid():
            return render(request, "encyclopedia/chosen-nobut.html", {
                "message":"This field may not be empty", 
                "form2":form2
            })

        text = form.cleaned_data["text"]
        with open(f"entries/{title}.md", 'w') as file:
            file.write(text) 
        html2 = util.get_entry(title)

        if not form.is_valid():
            return render(request, "encyclopedia/chosen-nobut.html", {
                "message":"This field may not be empty", 
                "form2":form2
            })
        else:
            text = markdown2.markdown(html2)
            return HttpResponseRedirect(f"/wiki/{title}")

    else:
        html2 = util.get_entry(title)
        return render(request, "encyclopedia/edit.html", {
            "form":NewTaskForm3({"text":html2}), 
            "form2":form2, 
            "TITLE":TITLE, 
            "title":title, 
            "TEXT":html2
        })

encyclopedia/templates/encyclopedia/chosen-nobut.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {{ message }}
    {{ text|safe }} 
{% endblock %}

encyclopedia/templates/encyclopedia/chosen.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {{ message }}
    {{ text|safe }} <br>
    <form action="{% url 'encyclopedia:edit' %}" method="get">
        <button type="submit">Edit text</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create the new file
{% endblock %}

{% block body %}
    <h1>Create the new page</h1>
    <form action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        {{ form }}<br>
        <input type="submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit the file already exists
{% endblock %}

{% block body %}
    <h1>Edit the file already exists</h1> <br>
    <form action="{% url 'encyclopedia:edit' %}" method="post">
        {% csrf_token %}
        {{ form }}<br>
        <input type="submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>{{ entry }}</li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <!-- <input class="search" type="text" name="q" placeholder="Search Encyclopedia"> -->
                    {{form2}}<br>
                    <input type="submit">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>